title:            Charlie Griefer
description:      I'm here to learn clojure and chew bubblegum.
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              http://charliegriefer.github.io
disqus_shortname:   charliegriefer-github-io

# Owner/author information
owner:
  name:           Charlie Griefer
  avatar:         bio-photo.png
  bio:            "I'm all out of bubblegum."
  email:          charlie@griefer.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:        charliegriefer
  facebook:
  github:         charliegriefer
  stackoverflow:  charliegriefer
  linkedin:       charliegriefer
  instagram:
  lastfm:
  tumblr:
  pinterest:
  foursquare:
  steam:
  dribbble:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-53448619-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about/
  - title: Posts
    url: /posts/
  - title: RSS
    url: /feed.xml
  - title: Second Half Charlie
    url: http://secondhalfcharlie.com
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Phoenix
future:      true
highlighter: pygments
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
# permalink:   /:categories/:title/
permalink: pretty

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
